spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/estudos}
    username: ${DB_USERNAME:estudos}
    password: ${DB_PASSWORD:estudos}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
