export type Lang = 'en' | 'pt';

export const S = {
  en: {
    tabTopics: 'Topics', tabCalendar: 'Calendar', tabCourses: 'Courses',
    tabReminders: 'Reminders', tabYou: 'You',
    cancel: 'Cancel', save: 'Save', create: 'Create', confirm: 'Confirm',
    delete: 'Delete', edit: 'Edit', add: 'Add', next: 'Next', back: 'Back',
    noTopics: 'No topics yet. Tap + to add one.',
    newTopic: 'New Topic', topicName: 'Topic name',
    addItem: 'Add Item', addCourse: 'Add Course',
    noItems: 'No items yet.',
    title: 'Title', description: 'Description', period: 'Period (e.g. Week 1)',
    weight: 'Weight', dueDate: 'Due date (YYYY-MM-DD)',
    type: 'Type', goal: 'Goal', theory: 'Theory', practice: 'Practice',
    pending: 'Pending', doing: 'In Progress', done: 'Done',
    totalInvested: 'Total invested', monthlyActive: 'Monthly active',
    platform: 'Platform', status: 'Status', payment: 'Payment',
    oneTime: 'One-time', subscription: 'Subscription',
    activeMonths: 'Active months', value: 'Value', currency: 'Currency',
    link: 'Link (optional)',
    planned: 'Planned', active: 'Active', paused: 'Paused', owned: 'Owned',
    noCourses: 'No courses yet. Tap + to add one.',
    noItemsDue: 'No items due.', assignItem: 'Assign item to this day',
    pickTopic: 'Pick a topic', pickItem: 'Pick an item',
    scheduleReminder: 'Schedule reminder', activeReminders: 'Active reminders',
    topicOptional: 'Topic (optional)', frequency: 'Frequency',
    daily: 'Daily', weekly: 'Weekly', custom: 'Custom', days: 'Days', time: 'Time',
    profile: 'Profile', language: 'Language', importCsv: 'Import CSV',
    chooseCsv: 'Choose CSV file', importN: (n: number) => `Import ${n} rows`,
    signOut: 'Sign out', signOutConfirm: 'Sign out?', signOutMsg: 'You will need to log in again.',
    welcomeAtlas: 'Welcome to Atlas', signIn: 'Sign in', signUp: 'Create account',
    emailLabel: 'Email', passwordLabel: 'Password', nameLabel: 'Your name',
    noAccount: "Don't have an account?", haveAccount: 'Already have an account?',
    register: 'Register', login: 'Log in',
    emailRequired: 'Email is required', passwordRequired: 'Password is required',
    nameRequired: 'Name is required', wrongCredentials: 'Email or password incorrect.',
    emailTaken: 'An account with this email already exists.',
    ob1Title: 'Track what matters', ob1Desc: 'Organise your studies into topics, goals, and courses — all in one place.',
    ob2Title: 'Stay on schedule', ob2Desc: 'Assign due dates to items and get notified before deadlines.',
    ob3Title: 'Measure progress', ob3Desc: 'Weighted progress rings show you exactly how far you\'ve come.',
    getStarted: 'Get started',
    syncComplete: 'Sync complete', syncFailed: 'Sync failed',
    importComplete: (items: number, courses: number) => `${items} items · ${courses} courses imported`,
    parseError: 'Could not read CSV', importFailed: 'Import failed',
  },
  pt: {
    tabTopics: 'Tópicos', tabCalendar: 'Calendário', tabCourses: 'Cursos',
    tabReminders: 'Lembretes', tabYou: 'Você',
    cancel: 'Cancelar', save: 'Salvar', create: 'Criar', confirm: 'Confirmar',
    delete: 'Excluir', edit: 'Editar', add: 'Adicionar', next: 'Próximo', back: 'Voltar',
    noTopics: 'Nenhum tópico ainda. Toque + para adicionar.',
    newTopic: 'Novo Tópico', topicName: 'Nome do tópico',
    addItem: 'Adicionar Item', addCourse: 'Adicionar Curso',
    noItems: 'Nenhum item ainda.',
    title: 'Título', description: 'Descrição', period: 'Período (ex: Semana 1)',
    weight: 'Peso', dueDate: 'Prazo (AAAA-MM-DD)',
    type: 'Tipo', goal: 'Meta', theory: 'Teoria', practice: 'Prática',
    pending: 'Pendente', doing: 'Fazendo', done: 'Concluído',
    totalInvested: 'Total investido', monthlyActive: 'Mensal ativo',
    platform: 'Plataforma', status: 'Status', payment: 'Pagamento',
    oneTime: 'Único', subscription: 'Assinatura',
    activeMonths: 'Meses ativos', value: 'Valor', currency: 'Moeda',
    link: 'Link (opcional)',
    planned: 'Planejado', active: 'Ativo', paused: 'Pausado', owned: 'Concluído',
    noCourses: 'Nenhum curso ainda. Toque + para adicionar.',
    noItemsDue: 'Nenhum item nesse dia.', assignItem: 'Atribuir item a este dia',
    pickTopic: 'Escolha um tópico', pickItem: 'Escolha um item',
    scheduleReminder: 'Agendar lembrete', activeReminders: 'Lembretes ativos',
    topicOptional: 'Tópico (opcional)', frequency: 'Frequência',
    daily: 'Diário', weekly: 'Semanal', custom: 'Personalizado', days: 'Dias', time: 'Hora',
    profile: 'Perfil', language: 'Idioma', importCsv: 'Importar CSV',
    chooseCsv: 'Escolher arquivo CSV', importN: (n: number) => `Importar ${n} linhas`,
    signOut: 'Sair', signOutConfirm: 'Sair da conta?', signOutMsg: 'Você precisará fazer login novamente.',
    welcomeAtlas: 'Bem-vindo ao Atlas', signIn: 'Entrar', signUp: 'Criar conta',
    emailLabel: 'Email', passwordLabel: 'Senha', nameLabel: 'Seu nome',
    noAccount: 'Não tem uma conta?', haveAccount: 'Já tem uma conta?',
    register: 'Cadastrar', login: 'Entrar',
    emailRequired: 'Email obrigatório', passwordRequired: 'Senha obrigatória',
    nameRequired: 'Nome obrigatório', wrongCredentials: 'Email ou senha incorretos.',
    emailTaken: 'Já existe uma conta com esse email.',
    ob1Title: 'Acompanhe o que importa', ob1Desc: 'Organize seus estudos em tópicos, metas e cursos — tudo em um só lugar.',
    ob2Title: 'Mantenha o ritmo', ob2Desc: 'Defina prazos para os itens e receba lembretes antes dos vencimentos.',
    ob3Title: 'Meça seu progresso', ob3Desc: 'Anéis de progresso ponderado mostram exatamente até onde você chegou.',
    getStarted: 'Começar',
    syncComplete: 'Sincronização completa', syncFailed: 'Falha na sincronização',
    importComplete: (items: number, courses: number) => `${items} itens · ${courses} cursos importados`,
    parseError: 'Não foi possível ler o CSV', importFailed: 'Falha na importação',
  },
} as const;

export type Strings = typeof S['en'];
