export type Lang = 'en' | 'pt';

export const S = {
  en: {
    tabTopics: 'Topics', tabCalendar: 'Calendar', tabCourses: 'Courses',
    tabReminders: 'Reminders', tabYou: 'You',
    cancel: 'Cancel', save: 'Save', create: 'Create', confirm: 'Confirm',
    delete: 'Delete', edit: 'Edit', add: 'Add', next: 'Next', back: 'Back',
    noTopics: 'No topics yet. Tap + to add one.',
    newTopic: 'New Topic', topicName: 'Topic name',
    addItem: 'Add Item', addCourse: 'Add Course',
    noItems: 'No items yet.',
    title: 'Title', description: 'Description', period: 'Period (e.g. Week 1)',
    weight: 'Weight', dueDate: 'Due date (YYYY-MM-DD)',
    type: 'Type', goal: 'Goal', theory: 'Theory', practice: 'Practice',
    pending: 'Pending', doing: 'In Progress', done: 'Done',
    totalInvested: 'Total invested', monthlyActive: 'Monthly active',
    platform: 'Platform', status: 'Status', payment: 'Payment',
    oneTime: 'One-time', subscription: 'Subscription',
    activeMonths: 'Active months', value: 'Value', currency: 'Currency',
    link: 'Link (optional)',
    planned: 'Planned', active: 'Active', paused: 'Paused', owned: 'Owned',
    noCourses: 'No courses yet. Tap + to add one.',
    noItemsDue: 'No items due.', assignItem: 'Assign item to this day',
    pickTopic: 'Pick a topic', pickItem: 'Pick an item',
    scheduleReminder: 'Schedule reminder', activeReminders: 'Active reminders',
    topicOptional: 'Topic (optional)', frequency: 'Frequency',
    daily: 'Daily', weekly: 'Weekly', custom: 'Custom', days: 'Days', time: 'Time',
    profile: 'Profile', language: 'Language', importCsv: 'Import CSV',
    chooseCsv: 'Choose CSV file', importN: (n: number) => `Import ${n} rows`,
    signOut: 'Sign out', signOutConfirm: 'Sign out?', signOutMsg: 'You will need to log in again.',
    welcomeAtlas: 'Welcome to Atlas', signIn: 'Sign in', signUp: 'Create account',
    emailLabel: 'Email', passwordLabel: 'Password', nameLabel: 'Your name',
    noAccount: "Don't have an account?", haveAccount: 'Already have an account?',
    register: 'Register', login: 'Log in',
    emailRequired: 'Email is required', passwordRequired: 'Password is required',
    nameRequired: 'Name is required', wrongCredentials: 'Email or password incorrect.',
    emailTaken: 'An account with this email already exists.',
    ob1Title: 'Track what matters', ob1Desc: 'Organise your studies into topics, goals, and courses — all in one place.',
    ob2Title: 'Stay on schedule', ob2Desc: 'Assign due dates to items and get notified before deadlines.',
    ob3Title: 'Measure progress', ob3Desc: 'Weighted progress rings show you exactly how far you\'ve come.',
    getStarted: 'Get started',
    syncComplete: 'Sync complete', syncFailed: 'Sync failed',
    importComplete: (items: number, courses: number) => `${items} items · ${courses} courses imported`,
    parseError: 'Could not read CSV', importFailed: 'Import failed',
    months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    weekdaysShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    weekdayInitials: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
    reminderScheduled: 'Reminder scheduled', reminderNextAt: (h: string) => `Next at ${h}`,
    rowsN: (n: number) => `${n} rows`, moreN: (n: number) => `+${n} more`,
    previewCount: (i: number, c: number) => `${i} items · ${c} courses`,
    csvHelp:
      'CSV columns: topico, tipo, titulo, descricao, onde, periodo, data_prevista, status, peso, pagamento, valor, moeda, progresso, link. ' +
      'tipo = meta / teoria / pratica (item) or curso (course); for courses "onde" is the platform. ' +
      'descricao becomes the item notes (tap an item to read/edit them). ' +
      'data_prevista uses YYYY-MM-DD. The topic is created automatically if it does not exist.',
    rememberMe: 'Remember me',
    deleteTopicConfirm: 'Delete this topic and all its items?',
    itemsProgress: (done: number, total: number) => `${done} of ${total} items`,
    notifReminderTitle: 'Time to study!', notifReminderDaily: 'Your daily reminder.',
    notifReminderBody: 'Your reminder.', notifDeadlineTitle: 'Atlas — deadline approaching',
    notes: 'Notes', notesPlaceholder: 'Write your notes here…', notesSaved: 'Notes saved',
  },
  pt: {
    tabTopics: 'Tópicos', tabCalendar: 'Calendário', tabCourses: 'Cursos',
    tabReminders: 'Lembretes', tabYou: 'Você',
    cancel: 'Cancelar', save: 'Salvar', create: 'Criar', confirm: 'Confirmar',
    delete: 'Excluir', edit: 'Editar', add: 'Adicionar', next: 'Próximo', back: 'Voltar',
    noTopics: 'Nenhum tópico ainda. Toque + para adicionar.',
    newTopic: 'Novo Tópico', topicName: 'Nome do tópico',
    addItem: 'Adicionar Item', addCourse: 'Adicionar Curso',
    noItems: 'Nenhum item ainda.',
    title: 'Título', description: 'Descrição', period: 'Período (ex: Semana 1)',
    weight: 'Peso', dueDate: 'Prazo (AAAA-MM-DD)',
    type: 'Tipo', goal: 'Meta', theory: 'Teoria', practice: 'Prática',
    pending: 'Pendente', doing: 'Fazendo', done: 'Concluído',
    totalInvested: 'Total investido', monthlyActive: 'Mensal ativo',
    platform: 'Plataforma', status: 'Status', payment: 'Pagamento',
    oneTime: 'Único', subscription: 'Assinatura',
    activeMonths: 'Meses ativos', value: 'Valor', currency: 'Moeda',
    link: 'Link (opcional)',
    planned: 'Planejado', active: 'Ativo', paused: 'Pausado', owned: 'Concluído',
    noCourses: 'Nenhum curso ainda. Toque + para adicionar.',
    noItemsDue: 'Nenhum item nesse dia.', assignItem: 'Atribuir item a este dia',
    pickTopic: 'Escolha um tópico', pickItem: 'Escolha um item',
    scheduleReminder: 'Agendar lembrete', activeReminders: 'Lembretes ativos',
    topicOptional: 'Tópico (opcional)', frequency: 'Frequência',
    daily: 'Diário', weekly: 'Semanal', custom: 'Personalizado', days: 'Dias', time: 'Hora',
    profile: 'Perfil', language: 'Idioma', importCsv: 'Importar CSV',
    chooseCsv: 'Escolher arquivo CSV', importN: (n: number) => `Importar ${n} linhas`,
    signOut: 'Sair', signOutConfirm: 'Sair da conta?', signOutMsg: 'Você precisará fazer login novamente.',
    welcomeAtlas: 'Bem-vindo ao Atlas', signIn: 'Entrar', signUp: 'Criar conta',
    emailLabel: 'Email', passwordLabel: 'Senha', nameLabel: 'Seu nome',
    noAccount: 'Não tem uma conta?', haveAccount: 'Já tem uma conta?',
    register: 'Cadastrar', login: 'Entrar',
    emailRequired: 'Email obrigatório', passwordRequired: 'Senha obrigatória',
    nameRequired: 'Nome obrigatório', wrongCredentials: 'Email ou senha incorretos.',
    emailTaken: 'Já existe uma conta com esse email.',
    ob1Title: 'Acompanhe o que importa', ob1Desc: 'Organize seus estudos em tópicos, metas e cursos — tudo em um só lugar.',
    ob2Title: 'Mantenha o ritmo', ob2Desc: 'Defina prazos para os itens e receba lembretes antes dos vencimentos.',
    ob3Title: 'Meça seu progresso', ob3Desc: 'Anéis de progresso ponderado mostram exatamente até onde você chegou.',
    getStarted: 'Começar',
    syncComplete: 'Sincronização completa', syncFailed: 'Falha na sincronização',
    importComplete: (items: number, courses: number) => `${items} itens · ${courses} cursos importados`,
    parseError: 'Não foi possível ler o CSV', importFailed: 'Falha na importação',
    months: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
    weekdaysShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
    weekdayInitials: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
    reminderScheduled: 'Lembrete agendado', reminderNextAt: (h: string) => `Próximo às ${h}`,
    rowsN: (n: number) => `${n} linhas`, moreN: (n: number) => `+${n} mais`,
    previewCount: (i: number, c: number) => `${i} itens · ${c} cursos`,
    csvHelp:
      'Colunas do CSV: topico, tipo, titulo, descricao, onde, periodo, data_prevista, status, peso, pagamento, valor, moeda, progresso, link. ' +
      'tipo = meta / teoria / pratica (item) ou curso; para cursos, "onde" é a plataforma. ' +
      'descricao vira as notas do item (toque no item para ler/editar). ' +
      'data_prevista no formato AAAA-MM-DD. O tópico é criado automaticamente se não existir.',
    rememberMe: 'Lembrar de mim',
    deleteTopicConfirm: 'Excluir este tópico e todos os seus itens?',
    itemsProgress: (done: number, total: number) => `${done} de ${total} itens`,
    notifReminderTitle: 'Hora de estudar!', notifReminderDaily: 'Seu lembrete diário.',
    notifReminderBody: 'Seu lembrete.', notifDeadlineTitle: 'Atlas — prazo chegando',
    notes: 'Notas', notesPlaceholder: 'Escreva suas notas aqui…', notesSaved: 'Notas salvas',
  },
} as const;

export type Strings = typeof S['en'];
